"""Initial migration

Revision ID: f7c72958bc52
Revises: 
Create Date: 2025-05-11 18:24:58.068928

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7c72958bc52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tests')
    op.drop_table('questions')
    op.drop_table('quizzes')
    op.drop_table('videos')
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=200), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=200), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('password_hash')

    op.create_table('videos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('video_url', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('uploaded_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('quizzes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('total_marks', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('questions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quiz_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_text', mysql.TEXT(), nullable=False),
    sa.Column('option_a', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('option_b', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('option_c', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('option_d', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('correct_option', mysql.VARCHAR(length=5), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name='questions_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tests',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('max_marks', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
